Repository PiotrKolecki/cookitpiteproject, pull requests merged in 2020-12, with the labels that each got.

#2 UI development
  CookIT/templates/base.html
  CookIT/templates/loginRegister.html
  CookIT/urls.py
  CookIT/views.py
  CookITServer/settings.py
  static/images/forkPlateKnife.png
  static/images/fries.png
  static/images/iceCream.png
  static/images/logo.png
  static/images/other.png
  static/images/salad.png
  static/images/toast.png
  static/scripts/loginRegisterValidators.js
  static/scripts/topBarButtons.js
  static/stylesSheets/loginRegister.css
  static/stylesSheets/mainStyles.css
Labels: enhancement

#7 Created tests for index and account views
  .github/workflows/django.yml
  CookIT/tests.py
Labels: enhancement

#8 redirect index to CookIT
  CookIT/gitTest.txt
  CookIT/migrations/0001_initial.py
  CookIT/migrations/__pycache__/0001_initial.cpython-38.pyc
  CookITServer/urls.py
Labels: bugfix

#9 Test db
  .github/workflows/django.yml
  CookIT/migrations/0001_initial.py
  CookIT/migrations/__pycache__/0001_initial.cpython-38.pyc
  CookIT/templates/account.html
  CookIT/templates/base.html
  CookIT/tests.py
  CookIT/views.py
  CookITServer/settings.py
Labels: bugfix, enhancement

#11 Database
  CookIT/models.py
  CookIT/tests.py
  CookITServer/settings.py
Labels: enhancement
